config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :interests
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "root#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests
  validates :name, presence: true, uniqueness: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_interests, dependent: :destroy
  has_many :user_skills, dependent: :destroy
  has_many :interests, through: :user_interests
  has_many :skills, through: :user_skills

  validates :email, uniqueness: { case_sensitive: false }

  enum :gender, { male: 0, female: 1 }

  def full_name
    "#{surname} #{name} #{patronymic}"
  end
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :interest
  belongs_to :user
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: %i[ show edit update destroy ]

  def index
    @interests = Interest.all
  end

  def show
  end

  def new
    @interest = Interest.new
  end

  def edit
  end

  def create
    @interest = Interest.new(interest_params)

    if @interest.save
      redirect_to @interest, notice: "Interest was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @interest.update(interest_params)
      redirect_to @interest, notice: "Interest was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @interest.destroy!
    redirect_to interests_path, status: :see_other, notice: "Interest was successfully destroyed."
  end

  private

  def set_interest
    @interest = Interest.find(params.expect(:id))
  end

  def interest_params
    params.fetch(:interest, {}).permit(:name)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]

  def index
    @skills = Skill.all
  end

  def show
  end

  def new
    @skill = Skill.new
  end

  def edit
  end

  def create
    @skill = Skill.new(skill_params)

    if @skill.save
      redirect_to @skill, notice: "Skill was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @skill.update(skill_params)
      redirect_to @skill, notice: "Skill was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @skill.destroy!
    redirect_to skills_path, status: :see_other, notice: "Skill was successfully destroyed."
  end

  private

  def set_skill
    @skill = Skill.find(params.expect(:id))
  end

  def skill_params
    params.fetch(:skill, {}).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    @user = Users::Update.new(user: @user)
  end

  def create
    outcome = Users::Create.run(user_params)
    if outcome.valid?
      redirect_to outcome.result, notice: "User was successfully created."
    else
      @user = outcome
      render :new, status: :unprocessable_entity
    end
  end

  def update
    outcome = Users::Update.run(user_params.merge(user: @user))
    if outcome.valid?
      redirect_to outcome.result, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    redirect_to users_path, status: :see_other, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params.expect(:id))
  end

  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/interests/_form.html.erb
<%= form_with(model: interest) do |form| %>
  <% if interest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
        <% interest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/interests/_interest.html.erb
<div id="<%= dom_id interest %>">
</div>

app/views/interests/edit.html.erb
<% content_for :title, "Editing interest" %>

<h1>Editing interest</h1>

<%= render "form", interest: @interest %>

<br>

<div>
  <%= link_to "Show this interest", @interest %> |
  <%= link_to "Back to interests", interests_path %>
</div>

app/views/interests/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Interests" %>

<h1>Interests</h1>

<div id="interests">
  <% @interests.each do |interest| %>
    <%= render interest %>
    <p>
      <%= link_to interest.name, interest %>
    </p>
  <% end %>
</div>

<%= link_to "New interest", new_interest_path %>

app/views/interests/new.html.erb
<% content_for :title, "New interest" %>

<h1>New interest</h1>

<%= render "form", interest: @interest %>

<br>

<div>
  <%= link_to "Back to interests", interests_path %>
</div>

app/views/interests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @interest %>

<div>
  <%= link_to "Edit this interest", edit_interest_path(@interest) %> |
  <%= link_to "Back to interests", interests_path %>

  <%= button_to "Destroy this interest", @interest, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test Task" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div>Home</div>

<p>
  <%= link_to "Users", users_path %>
</p>
<p>
  <%= link_to "Skills", skills_path %>
</p>
<p>
  <%= link_to "Interests", interests_path %>
</p

app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/_skill.html.erb
<div id="<%= dom_id skill %>">
</div>

app/views/skills/edit.html.erb
<% content_for :title, "Editing skill" %>

<h1>Editing skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Show this skill", @skill %> |
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Skills" %>

<h1>Skills</h1>

<div id="skills">
  <% @skills.each do |skill| %>
    <%= render skill %>
    <p>
      <%= link_to skill.name, skill %>
    </p>
  <% end %>
</div>

<%= link_to "New skill", new_skill_path %>

app/views/skills/new.html.erb
<% content_for :title, "New skill" %>

<h1>New skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skill %>

<div>
  <%= link_to "Edit this skill", edit_skill_path(@skill) %> |
  <%= link_to "Back to skills", skills_path %>

  <%= button_to "Destroy this skill", @skill, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :patronymic, "Patronymic" %>
    <%= form.text_field :patronymic %>
  </div>
    <%= form.label :surname, "Surname" %>
    <%= form.text_field :surname %>
  <div>
    <%= form.label :email, "Email" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :age, "Age" %>
    <%= form.number_field :age %>
  </div>
  <div>
    <%= form.label :nationality, "Nationality" %>
    <%= form.text_field :nationality %>
  </div>
  <div>
    <%= form.label :country, "Country" %>
    <%= form.text_field :country %>
  </div>
  <div>
    <%= form.label :gender, "Gender" %>
    <%= form.select :gender, User.genders.to_a %>
  </div>

  <% if user.persisted? %>
    <div>
        <% form.label :interests, "Interests" %>
        <%= form.collection_select :interests, Interest.all, :id, :name, {selected: user.interests}, multiple: true %>
    </div>
    <div>
        <% form.label :skills, "Skills" %>
        <%= form.collection_select :skills, Skill.all, :id, :name, {selected: user.skills}, multiple: true %>
    </div>
  <% else %>
    <div>
        <% form.label :interests, "Interests" %>
        <%= form.collection_select :interests, Interest.all, :id, :name, multiple: true %>
    </div>
    <div>
        <% form.label :skills, "Skills" %>
        <%= form.collection_select :skills, Skill.all, :id, :name, multiple: true %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
    <div>
      Email: <%= user.email %>
    </div>
    <div>
      Full name: <%= user.full_name %>
    </div>
    <div>
      Age: <%= user.age %>
    </div>
    <div>
      Nationality: <%= user.nationality %>
    </div>
    <div>
      Country: <%= user.country %>
    </div>
    <div>
      Gender: <%= user.gender %>
    </div>
    <div>
      Interests: <%= user.interests.pluck(:name).join(", ") %>
    </div>
    <div>
      Skills: <%= user.skills.pluck(:name).join(", ") %>
    </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <p>
      <%= link_to user.email, user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>